# Generated by Django 6.0.1 on 2026-02-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='community',
            field=models.CharField(choices=[('bihari', 'Bihari Bride'), ('tamil', 'Tamil Bride'), ('telugu', 'Telugu Bride'), ('kannada', 'Kannadiga Bride'), ('gujarati', 'Gujarati Bride'), ('marathi', 'Marathi Bride'), ('bengali', 'Bengali Bride'), ('punjabi', 'Punjabi Bride'), ('up', 'UP Bride'), ('marwari', 'Marwari Bride'), ('odia', 'Odia Bride'), ('muslim', 'Muslim Bride')], default='bihari', max_length=50),
            preserve_default=False,
        ),
    ]
